# Generated by Django 4.0.2 on 2022-06-08 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProduco', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=100)),
                ('precioProducto', models.IntegerField()),
                ('descripcionProducto', models.CharField(max_length=300)),
                ('disponibilidadProducto', models.BooleanField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categoria')),
            ],
        ),
    ]
