# Generated by Django 4.0.2 on 2022-06-22 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_producto_descripcionproducto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='detalleFactura',
            fields=[
                ('idDetalleFactura', models.IntegerField(primary_key=True, serialize=False)),
                ('idFactura', models.IntegerField(verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.factura'))),
                ('nroItem', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='porcentageSuscripcion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='procentageOferta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellidoUsuario',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='suscripcionUsusario',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='productoBodega',
            fields=[
                ('idProductoBodega', models.IntegerField(primary_key=True, serialize=False)),
                ('idDetalleFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.detallefactura')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.producto')),
            ],
        ),
        migrations.CreateModel(
            name='factura',
            fields=[
                ('idFactura', models.IntegerField(primary_key=True, serialize=False)),
                ('nroFactura', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estadoFactura', models.CharField(max_length=50)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usuario')),
            ],
        ),
    ]
