# Generated by Django 4.0.5 on 2022-06-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_detallefactura_producto_porcentagesuscripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagenProducto',
            field=models.ImageField(default='sinfoto.jpg', upload_to='media/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidoUsuario',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagenUsuario',
            field=models.ImageField(default='sinfoto.jpg', upload_to='media/', verbose_name='Imagen'),
        ),
    ]
