# Generated by Django 4.0.4 on 2022-07-04 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_usuario_last_login_usuario_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='password',
        ),
    ]
