# Generated by Django 4.0.2 on 2022-06-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categoriausuario_producto_imagenproducto_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcionProducto',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='producto',
            name='disponibilidadProducto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagenProducto',
            field=models.ImageField(default='sinfoto.jpg', upload_to='images/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagenUsuario',
            field=models.ImageField(upload_to=''),
        ),
    ]
