# Generated by Django 4.0.5 on 2022-07-01 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_usuario_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutUsuario', models.CharField(max_length=10, unique=True)),
                ('direccionUsusario', models.CharField(max_length=300, verbose_name='Direccion Usuario')),
                ('suscripcionUsusario', models.BooleanField(default=False, verbose_name='Suscriptor')),
                ('imagenUsuario', models.ImageField(default='sinfoto.jpg', upload_to='images/', verbose_name='Imagen Usuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='CategoriaUsuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
