# Generated by Django 4.0.5 on 2022-07-03 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_perfilusuario_rutusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroFactura', models.IntegerField(verbose_name='Nro Item')),
                ('fecha', models.DateField(verbose_name='Fecha Factura')),
                ('estado', models.CharField(default='B', max_length=1, verbose_name='Fecha Factura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroItem', models.IntegerField(verbose_name='Nro Factura')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('direccionUsusario', models.CharField(max_length=300, verbose_name='Direccion Usuario')),
                ('suscripcionUsusario', models.BooleanField(default=False, verbose_name='Suscriptor')),
                ('precioFinal', models.IntegerField(verbose_name='Precio Final')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.factura')),
            ],
        ),
    ]
