# Generated by Django 4.0.5 on 2022-07-13 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_factura_detallefactura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='nroFactura',
        ),
    ]
