# Generated by Django 4.0.5 on 2022-07-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_factura_nrofactura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='nroItem',
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='nomProducto',
            field=models.CharField(max_length=300, null=True, verbose_name='Nombre Producto'),
        ),
    ]
