# Generated by Django 4.0.5 on 2022-07-13 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_detallefactura_nomproducto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='suscripcionUsusario',
        ),
    ]
