# Generated by Django 4.0.5 on 2022-07-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_detallefactura_suscripcionususario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='idProducto',
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='cateProducto',
            field=models.CharField(max_length=300, null=True, verbose_name='Categoria Producto'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='nomProducto',
            field=models.CharField(max_length=300, null=True, verbose_name='Nombre Producto'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='porcDesctoOferta',
            field=models.IntegerField(default=0, verbose_name='Porcentaje Descuento Oferta'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='porcDesctoSubscriptor',
            field=models.IntegerField(default=0, verbose_name='Porcentaje Descuento Suscriptor'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='precio',
            field=models.IntegerField(default=1, verbose_name='Precio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='suscripcionUsusario',
            field=models.BooleanField(default=False, verbose_name='Suscriptor'),
        ),
    ]
