# Generated by Django 4.0.5 on 2022-07-13 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_detallefactura_idproducto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='suscripcionUsusario',
        ),
    ]
